---
name: prolog-programming-task
version: 0.1.0.0
github: "fmidue/prolog-programming-task"
license: MIT
maintainer: "marcellus.siegburg@uni-due.de"
copyright: "2020 Formal Methods in Computer Science - University of Duisburg-Essen"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: A task type for prolog programming developed for the e-learning platform Autotool
category: E-Learning

description: Please see the README on GitHub at <https://github.com/fmidue/prolog-programming-task#readme>

dependencies:
  - MonadRandom
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - mtl
  - parsec
  - prolog
  - prolog-graph-lib >= 0.3.2
  - random-shuffle
  - raw-strings-qq
  - text
  - wl-pprint-text
  - syb >= 0.3

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
    - -Wincomplete-patterns
    - -Wincomplete-uni-patterns
  exposed-modules:
    - Prolog.Programming.Data
    - Prolog.Programming.Task
    - Prolog.Programming.CodeAnalysis
    - Prolog.Programming.CodeAnalysis.Types
    - Prolog.Programming.CodeAnalysis.Config

executables:
  test-task-prolog:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - prolog-programming-task

tests:
  prolog-programming-task-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - prolog-programming-task
      - HUnit
      - hspec
