---
name: Formatting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: read-all

jobs:
  build:
    name: Check format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run fourmolu
        uses: haskell-actions/run-fourmolu@v13
        with:
          version: "0.20.1.0"
          # Types.hs is only excluded since there are currently issues with formatting. See https://github.com/fourmolu/fourmolu/issues/552
          pattern: |
            **/*.hs
            !src/Prolog/Programming/CodeAnalysis/Types.hs
