---
name: Haskell CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions: read-all

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        plan:
          - {build: stack}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Cache Stack
        id: cache-stack-unix
        uses: actions/cache@v6
        with:
          path: '~/.stack'
          key: ${{ matrix.os }}-${{ matrix.plan.build }}-stack-home-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/package.yaml') }}

      - name: Setup stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: install/restore apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: graphviz texlive-base texlive-latex-base
          version: 1.0

      - name: Install dependencies
        run: |
          set -ex
          stack --no-terminal --install-ghc build --test --bench --only-dependencies
          set +ex
        env:
          BUILD: ${{ matrix.plan.build }}

      - name: Build and test
        run: |
          set -ex
          stack --no-terminal test --coverage --haddock --no-haddock-deps
          set +ex
        env:
          BUILD: ${{ matrix.plan.build }}
